### ISSUE TITLE
More flexibility when plotting movement data and fitted distributions

### ISSUE THREAD

**Issue by bniebuhr** [TheoMichelot/moveHMM#12]
Dear all,

I am starting to work with the moveHMM package. 
The package has some very nice functions that already plot several pieces of information together, such as the plot.moveData for moveData objects and plot.moveHMM for fitted models. However, I would like some flexibility for plotting that.
For example, if I want to use plot.moveData to plot, in a single figure, the map with relocations in a large plot and the four little plots at the side, exactly like Figure 2 from the vignette, how should I proceed?
(the same question could apply for plot.moveHMM).

I tried to use par(mfrow...) and layout() but I could make it.

Thanks in advance,
Bernardo Niebuhr

**Comment by TheoMichelot** [comment]
For something that looks like Figure 3 of the vignette, the most straightforward option is to save the four plots separately, and choose the overall layout outside of R. This is what we do in the vignette.
If you want to write a more flexible function, then you can have a look at the source code of `plot.moveHMM`.

You can also read the documentation of `fitHMM`, in which the format of the output object is detailed. In particular, for a moveHMM model `m`, `m$mle` contains the parameter estimates. With these, you can plot the estimated state-dependent densities for the step lengths and turning angles.
Then, you can use `viterbi` to obtain the most likely state sequence, and plot the colour-coded track.

Plotting the transition probabilities as functions of covariates would be a bit more difficult, but the theory is explained in Section 4.1.3 of the vignette.

I hope this helps.
Théo

**Comment by bniebuhr** [comment]
Hi Théo,
thanks, this will help me a lot!Best,Bernardo
    Em sábado, 21 de julho de 2018 06:47:46 BRT, Théo Michelot <notifications@github.com> escreveu:  
 
 
For something that looks like Figure 3 of the vignette, the most straightforward option is to save the four plots separately, and choose the overall layout outside of R. This is what we do in the vignette.
If you want to write a more flexible function, then you can have a look at the source code of plot.moveHMM.

You can also read the documentation of fitHMM, in which the format of the output object is detailed. In particular, for a moveHMM model m, m$mle contains the parameter estimates. With these, you can plot the estimated state-dependent densities for the step lengths and turning angles.
Then, you can use viterbi to obtain the most likely state sequence, and plot the colour-coded track.

Plotting the transition probabilities as functions of covariates would be a bit more difficult, but the theory is explained in Section 4.1.3 of the vignette.

I hope this helps.
Théo
