### ISSUE TITLE
Error in f(x, ...) : Wrong number of parameters in wpar.

### ISSUE THREAD

**Issue by RussellGrayxd** [TheoMichelot/moveHMM#16]
I have used all of the functions in the moveHMM package in the past with no issues... I've now used the fitHMM() function with a new set of data and run this error:
Error in f(x, ...) : Wrong number of parameters in wpar.

All of my parameters match the 2 step model that I'm trying to run, so I tried to use the vignette code found here: https://cran.r-project.org/web/packages/moveHMM/vignettes/moveHMM-guide.pdf
to troubleshoot the issue, and now the vignette code doesn't work either. 

I'm not sure what's going on. Has there been any update or modification recently which would mes with the package functionality??

**Comment by TheoMichelot** [comment]
Hello,

There hasn't been any recent update of the package. From your message, it is difficult to know what is going wrong. Are you saying that running the vignette code from scratch fails?

Could you perhaps provide a bit more information, e.g. the first few rows of your data set, and the exact fitHMM command you use to fit the model? Alternatively, you could contact me via email (tm75@st-andrews.ac.uk), to send me the script that produces the error.

Best wishes,
Théo

**Comment by RussellGrayxd** [comment]
Hey Theo,
I figured it out... the error was in the prepdata() function... I guess the covariates in the dataframe being fed to it have to be after the x and y coordinates and not before... I switched the column order and it works now. 

Best,
-RG
    On Friday, December 20, 2019, 08:14:48 p.m. GMT+7, Théo Michelot <notifications@github.com> wrote:  
 
 
Hello,

There hasn't been any recent update of the package. From your message, it is difficult to know what is going wrong. Are you saying that running the vignette code from scratch fails?

Could you perhaps provide a bit more information, e.g. the first few rows of your data set, and the exact fitHMM command you use to fit the model? Alternatively, you could contact me via email (tm75@st-andrews.ac.uk), to send me the script that produces the error.

Best wishes,
Théo

**Comment by TheoMichelot** [comment]
Okay, glad to hear that you solved the issue.

I think that, regardless of the indices of the covariate columns in the raw data set, prepData re-orders the columns and puts the covariates at the end.

Best wishes,
Théo
