### ISSUE TITLE
Animals observations must be contiguous

### ISSUE THREAD

**Issue by scra88le** [TheoMichelot/moveHMM#19]
Hi, I have come across a problem when attempting to use the `prepData` function. When I have one track (one animal) the function runs fine. When I have multiple animals (each with its own unique ID), I have the following error:

`Error in prepData(top_five_obs, type = "LL", coordNames = c("location.long", : Each animal's obervations must be contiguous.`

Is there a way of sorting the track data to correct this problem? When I eyeball the data, it looks to be in the right sequence to me.

**Comment by TheoMichelot** [comment]
I posted a suggestion on StackOverflow a while ago: stackoverflow.com/questions/57801154/error-in-prepdata-function-in-package-movehmm-contiguous-data/

I hope this helps,
Théo

**Comment by scra88le** [comment]
That solved the problem. Thank you!
