### ISSUE TITLE
Issue with state swapping

### ISSUE THREAD

**Issue by LucyJMitchell** [TheoMichelot/moveHMM#20]
Hi,

I'm having a slightly weird issue that I haven't had before. I'm using moveHMM on GPS data collected from birds at 3 and 5 minute fixes. I'm modelling these separately -also separating by sex because there seemed to be enough difference in step length parameters between males and females to warrant that.

I am running a 3 state model, resting, foraging, travelling, with resting being small steps, tight angles, foraging being medium steps, tight angles and travelling being long steps and 0 degree angles. 
This is an example of my starting values - smallest on the left, largest on the right. 

```
stepM_m3<-c(6,50,120)
stepSD_m3<-c(6,50,120) 
zeromass_m3<-c(0.1,0,0)
stepPar_m3<-c(stepM_m3,stepSD_m3,zeromass_m3)  
angleM_m3<-c(pi,2,0)  
angleC_m3<-c(10,2,2)  
anglePar_m3<-c(angleM_m3,angleC_m3)
```
I have also run a set of different random starting values as below: 

```
set.seed(12345)
niter <- 25
allm3m <- list()
for(i in 1:niter) {
  
  stepMean0 <- runif(3,
                     min = c(6,18,80),
                     max = c(18,80,120))
  
  stepSD0 <- runif(3,
                   min = c(6,18,80),
                   max = c(18,80,120))
  stepZM0<-c(0.0001,0,0)
  angleMean0 <- c(pi,pi, 0)
  angleCon0 <- runif(3,
                     min = c(2,0.5,0.1),
                     max = c(20,5,2))
  
  stepPar0 <- c(stepMean0, stepSD0,stepZM0)
  anglePar0 <- c(angleMean0, angleCon0)
  allm3m[[i]] <- fitHMM(data = m3sub, nbStates = 3, stepPar0 = stepPar0,
                      anglePar0 = anglePar0)
}
allm3k <- unlist(lapply(allm3m, function(m) m$mod$minimum))
allm3k

best3mal<-which.min(allm3k)
```

However, outputs show that the model has the foraging state (I programmed this as state 2) as state 1, and the resting state (the smallest parameters, so state 1) as state 2:

```
Value of the maximum log-likelihood: -65770.76 

Step length parameters:
----------------------
               state 1      state 2      state 3
mean      61.742700897 8.752272e+00 2.969460e+02
sd        57.843085364 5.688167e+00 3.203951e+02
zero-mass  0.000336713 9.871821e-09 1.005928e-08

Turning angle parameters:
------------------------
                state 1   state 2     state 3
mean          3.1032134 3.1341238 -0.02010938
concentration 0.6147991 0.6710232  0.25189325

Regression coeffs for the transition probabilities:
--------------------------------------------------
             1 -> 2    1 -> 3    2 -> 1    2 -> 3    3 -> 1    3 -> 2
intercept -1.455355 -2.382141 -1.962339 -2.723177 -2.300269 -1.925488
```

This happens when I let R choose the starting values as well, although it does also produce some models which have the states in the correct order, although these have 'worse' max likelihood, and are much less frequent in the set of 25 model outputs than the models with the states in the wrong order, as you'll see here:

```
[[24]]
Value of the maximum log-likelihood: -65774.11 

Step length parameters:
----------------------
               state 1      state 2      state 3
mean      8.7499433298 6.175918e+01 2.967334e+02
sd        5.6854784015 5.781326e+01 3.202550e+02
zero-mass 0.0002140869 1.012813e-08 1.004517e-08

Turning angle parameters:
------------------------
               state 1   state 2     state 3
mean          3.134141 3.1032746 -0.01993093
concentration 0.670662 0.6157627  0.25155457

Regression coeffs for the transition probabilities:
--------------------------------------------------
             1 -> 2    1 -> 3    2 -> 1   2 -> 3    3 -> 1    3 -> 2
intercept -1.955506 -2.722793 -1.446135 -2.37923 -1.924119 -2.306001

Transition probability matrix:
-----------------------------
          [,1]       [,2]       [,3]
[1,] 0.8283742 0.11720904 0.05441673
[2,] 0.1773048 0.75295504 0.06974012
[3,] 0.1172101 0.08000474 0.80278519

Initial distribution:
--------------------
[1] 7.633490e-01 2.366163e-01 3.461621e-05

[[25]]
Value of the maximum log-likelihood: -65770.76 

Step length parameters:
----------------------
               state 1      state 2      state 3
mean      6.174260e+01 8.752271e+00 2.969442e+02
sd        5.784298e+01 5.688168e+00 3.203945e+02
zero-mass 3.366996e-04 9.947500e-09 1.004848e-08

Turning angle parameters:
------------------------
                state 1   state 2     state 3
mean          3.1032161 3.1341230 -0.02009984
concentration 0.6148002 0.6710255  0.25189513

Regression coeffs for the transition probabilities:
--------------------------------------------------
             1 -> 2   1 -> 3    2 -> 1    2 -> 3    3 -> 1    3 -> 2
intercept -1.455364 -2.38213 -1.962345 -2.723182 -2.300256 -1.925505

Transition probability matrix:
-----------------------------
          [,1]      [,2]       [,3]
[1,] 0.7543360 0.1759983 0.06966566
[2,] 0.1165057 0.8290540 0.05444025
[3,] 0.0804417 0.1170128 0.80254550

Initial distribution:
--------------------
[1] 2.365508e-01 7.634474e-01 1.748140e-06

```

I have run this data through HMMs before but in different 'batches' of data, but this issue hasn't happened before. I'm unsure why this is happening and essentially I'm wondering if it's a problem, because the values for the states look ok. If they were the right way round i wouldn't be confused, as the values themselves would make sense. 

I have messed around with some of the parameters, mostly zero mass and both angle parameters.. I thought zero mass might be causing some problems because only a few points are actually zero so the zero mass for the resting state is something like 0.0008. But this either doesn't make a difference, or succeeds in changing the resting state step length parameter value to 0.001 or something similar - which is too small because as I said only 1 or 2 points are actually 0. 
Changing the angles also makes no difference - there are tall peaks at pi and -pi, but barely a peak at 0, and I've tried to represent this in the angle mean and concentration parameters, but it doesn't seem to matter. 

I assume I have just programmed something in incorrectly, although I'm just not sure what! Any advice much appreciated.

**Comment by TheoMichelot** [comment]
Hi Lucy,

This is a common situation, called "label switching". The labels "state 1", "state 2", ..., are arbitrary, and we don't change the model by switching them. So, you could just go ahead and use the model with the highest log-likelihood, and only change your interpretation of the states (state 2 would be slow movement, state 3 fast movement, and state 1 would be intermediate).

You could perhaps avoid this by choosing different ranges for the starting parameters, maybe something like:
``` R
stepMean0 <- runif(3,
                   min = c(5, 40, 200),
                   max = c(15, 80, 400))
  
stepSD0 <- runif(3,
                 min = c(5, 40, 200),
                 max = c(15, 80, 400))

stepZM0 <- c(0.0001, 0, 0)

angleMean0 <- c(pi, pi, 0)
  
angleCon0 <- runif(3,
                   min = c(0.1, 0.1, 0.1),
                   max = c(1, 1, 1))
```

I've just made the ranges more distinct for the parameters of the step lengths, to make sure that the starting values are quite different between the different states, and in the correct order (smaller for state 1, larger for state 3). I'm not sure if this will make a difference, but you can give it a try. Eventually, you should use the model with the best likelihood.

I hope this helps.

Best wishes,
Théo

**Comment by LucyJMitchell** [comment]
Thank you Théo, I think I understand. I’ll try that now and see what happens. I thought perhaps it would be incorrect to have programmed the first state as the smallest but for that to be interpreted as state 2, but if it doesn’t ‘change’ back, at least I can interpret it correctly.

Best wishes,
Lucy

Dr Lucy Mitchell
Postdoctoral Research Assistant Ornithological Migration
Department of Biological and Marine Sciences
University of Hull
HU6 7RX

https://www.researchgate.net/profile/Lucy_Mitchell11
https://www.linkedin.com/in/lucy-mitchell-2b979955/
@lucyjayneryan
https://univhullornithgroup.wixsite.com/horc

**Comment by TheoMichelot** [comment]
Great, good luck with the analysis. Let me know if you have any other questions.

Best wishes,
Théo
