### ISSUE TITLE
prepData Error

### ISSUE THREAD

**Issue by milliff** [TheoMichelot/moveHMM#22]
Hello!

I am trying to use the prepData command on a large dataframe and am getting the following error:

Error: Positive column indexes in `[` must match number of columns:
* `.data` has 1 columns
* Position 1 equals 2

Unfortunately, when I call rlang::last_error(), no error is recorded. Does that error message give enough information to trace back the problem? I cannot see, looking at the function code, where it would have been invoked.

**Comment by TheoMichelot** [comment]
Hi,

There seems to be an error with how a data frame is being subset, but it's hard to tell where! Could you please send the output of `head(raw_data)`, where `raw_data` is the data frame that you pass to prepData?

Cheers,
Théo

**Comment by FlukeAndFeather** [comment]
I just ran into something similar. I think it has to do with tibbles vs data.frames. If I pipe a tibble through `as.data.frame()` before calling `prepData()` I don't see the error. I'll try to make a minimum reproducible example.

**Comment by FlukeAndFeather** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
set.seed(10)
x <- runif(10)
y <- runif(10)
data.frame(ID = 1, x, y) %>% 
    moveHMM::prepData()
#>    ID     step     angle          x          y
#> 1   1 24.19187        NA 0.50747820 0.65165567
#> 2   1 51.97540  1.437400 0.30676851 0.56773775
#> 3   1 61.01983  2.374310 0.42690767 0.11350898
#> 4   1 72.60754  2.448485 0.69310208 0.59592531
#> 5   1 17.46799 -3.047799 0.08513597 0.35804998
#> 6   1 42.03244 -1.904844 0.22543662 0.42880942
#> 7   1 23.47313  3.021757 0.27453052 0.05190332
#> 8   1 41.03489 -1.210136 0.27230507 0.26417767
#> 9   1 52.61096  1.604396 0.61582931 0.39879073
#> 10  1       NA        NA 0.42967153 0.83613414
tibble(ID = 1, x, y) %>% 
    moveHMM::prepData()
#> Error: Can't subset columns that don't exist.
#> x Location 2 doesn't exist.
#> ℹ There are only 1 column.
```

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by TheoMichelot** [comment]
Great, thanks Max for figuring this out.
