### ISSUE TITLE
steps > 0 after steps == 0 lose angle data

### ISSUE THREAD

**Issue by jojanzing** [TheoMichelot/moveHMM#23]
Hi! Nice package, thanks for making it.

I'm trying to fit an HMM to some movement data that contains steps of length zero. 

However, I've noticed that if there's a zero-length step at time `t`, the non-zero-length step at time `t+1` doesn't have any angular information. That makes sense in that there's no angle between steps `t` and `t+1`, but shouldn't the angle of step `t+1` be computed relative to the non-zero-length step at `t-1`?

So, if the animal was heading due East at `t-1`, stays put at `t`, then heads due North at `t+1`, shouldn't the heading of step `t+1` be `pi/2`, the angle between the headings at `t-1` and `t+1`?

Is there a way to toggle this behaviour in the package?

**Comment by TheoMichelot** [comment]
Hi, thanks for your message.

I don't think that we would want that behaviour in general, but you can use something like the following code.

``` R
# Create dummy data set
df <- data.frame(x = cumsum(rnorm(10)), y = cumsum(rnorm(10)))
df[6,] <- df[5,] # duplicate location to get step of length zero
data <- prepData(df, type = "UTM")
```
After this, `data` is something like
``` R
        ID      step       angle          x          y
1  Animal1 0.4309323          NA -0.6264538  1.5117812
2  Animal1 1.0412565  2.65032311 -0.4428105  1.9016244
3  Animal1 2.7294352  1.55573646 -1.2784391  1.2803838
4  Animal1 1.1721966  2.23241933  0.3168417 -0.9343161
5  Animal1 0.0000000          NA  0.6463495  0.1906149
6  Animal1 0.3386020          NA  0.6463495  0.1906149
7  Animal1 1.1983114 -2.41613922  0.3133101  0.1294910
8  Animal1 1.0029598  0.05234672  1.0516348  1.0733272
9  Animal1 0.6678180  1.08643149  1.6274162  1.8945484
10 Animal1        NA          NA  1.3220278  2.4884497
```
with the two missing angles in the middle (rows 5 and 6).

``` R
# Loop over steps of length zero
wh_zero_step <- which(data$step == 0)
for(i in wh_zero_step) {
    # Find the three points that define the angle
    points <- as.matrix(data[c(i-1, i+1, i+2), c("x", "y")])

    # Get turning angle using internal moveHMM function
    data$angle[i + 1] <- moveHMM:::turnAngle(x = points[1,], 
                                             y = points[2,], 
                                             z = points[3,], 
                                             LLangle = FALSE)    
}
```

I think that this should fill in the missing angles, e.g.,
``` R
        ID      step       angle          x          y
1  Animal1 0.4309323          NA -0.6264538  1.5117812
2  Animal1 1.0412565  2.65032311 -0.4428105  1.9016244
3  Animal1 2.7294352  1.55573646 -1.2784391  1.2803838
4  Animal1 1.1721966  2.23241933  0.3168417 -0.9343161
5  Animal1 0.0000000          NA  0.6463495  0.1906149
6  Animal1 0.3386020  2.03725281  0.6463495  0.1906149
7  Animal1 1.1983114 -2.41613922  0.3133101  0.1294910
8  Animal1 1.0029598  0.05234672  1.0516348  1.0733272
9  Animal1 0.6678180  1.08643149  1.6274162  1.8945484
10 Animal1        NA          NA  1.3220278  2.4884497
```

The angle on row 6 is not missing any more. You might want to double check that this computes the angle that you are interested in (i.e., between steps at times t-1 and t+1).

I hope this helps!

Théo

**Comment by jojanzing** [comment]
Hi Theo,

Thanks for the quick response! I realise this behaviour might be specific to my use case. Thanks for the code snippet, I will try it out =)
