### ISSUE TITLE
`allProbs()` is documented but not exported

### ISSUE THREAD

**Issue by FlukeAndFeather** [TheoMichelot/moveHMM#29]
`allProbs()` is in the package index (`help(package = "moveHMM")`) but it's not an exported function. So `?moveHMM::allProbs()` brings up the documentation, but `moveHMM::allProbs()` returns an error. 

I think the fix is to add `@keywords internal` to the roxygen comments.

**Comment by TheoMichelot** [comment]
Good point, thanks. Several other functions have the same problem, so I will need to think about whether they should all be hidden from the package index or not.
