### ISSUE TITLE
Issue with plot() of data

### ISSUE THREAD

**Issue by afateigeruri** [TheoMichelot/moveHMM#33]
To preface, I have a dataset that is prepped, and the fitHMM function works fine and I receive a reasonable output.  I have an issue with when I try to `plot(b, plotCI=TRUE)` I received the following error: "Decoding states sequence... Error in p[1, ] : incorrect number of dimensions". 
I started going back through the functions and for some reason, it looks like certain functions from the moveHMM package disappear and I have to rerun them manually from the r code listed here on the GitHub page (but so many of them give errors and I have to keep digging backward).  
plotStationary works just fine, and when I run the code on example data, the library also works fine.  However, when I run my data with either `plot(b, plotCI=TRUE)` or `plot(b, animals=1, ask=F)` or `viterbi(b)` I receive the same error in dimensions.
I have checked my function compared to examples in the vignette and they are the exact same (of course with just different values).  Any help or advice would be greatly appreciated!

**Comment by TheoMichelot** [comment]
It seems that something is going wrong on [line 75 of viterbi.R](https://github.com/TheoMichelot/moveHMM/blob/c48c93ae9436d58a8798d55482d1b2653dd2b07a/R/viterbi.R#L75), but without more information, it's hard for me to say what the problem is. Could you show what the parameter estimates look like (i.e., the output of printing `b` in the command line)?

**Comment by afateigeruri** [comment]
`Value of the maximum log-likelihood: -3034.105 

Step length parameters:
----------------------
               state 1   state 2
mean      4.086286e-02 0.5665334
sd        3.659942e-02 0.7533184
zero-mass 1.600063e-11 0.1054631

Turning angle parameters:
------------------------
                 state 1     state 2
mean          -3.1338442 -0.12934985
concentration  0.5771887  0.05792989

Regression coeffs for the transition probabilities:
--------------------------------------------------
                 1 -> 2        2 -> 1
intercept -1.922169e+00 -0.6723944252
cumprecip -3.478202e-05 -0.0002855905

Initial distribution:
--------------------
[1] 0.4650351 0.5349649`

**Comment by TheoMichelot** [comment]
Hmm, nothing raises a red flag here either, so I'm still not sure what the problem is.

Could you show the output of the following command:
``` R
obs_pdf <- moveHMM:::allProbs(data = hmm$data, 
                              nbStates = ncol(hmm$mle$stepPar), 
                              stepDist = hmm$conditions$stepDist,
                              angleDist = hmm$conditions$angleDist, 
                              stepPar = hmm$mle$stepPar, 
                              anglePar = hmm$mle$anglePar, 
                              zeroInflation = hmm$conditions$zeroInflation, 
                              knownStates = hmm$knownStates)

head(obs_pdf)
```

**Comment by afateigeruri** [comment]
Hi Theo,

Here is the output

'             [,1]       [,2]
[1,] 8.491860e-02 0.20828563
[2,] 4.082015e+00 0.44935669
[3,] 1.271895e+00 0.44969598
[4,] 8.730803e-07 0.07630139
[5,] 1.394291e+00 0.38710539
[6,] 3.505622e+00 0.38495862'

Thank you,
Anna

**Comment by TheoMichelot** [comment]
Still nothing obvious. Would you mind contacting me by email? (tm75@st-andrews.ac.uk)
