### ISSUE TITLE
Model moving direction

### ISSUE THREAD

**Issue by EDiLD** [TheoMichelot/moveHMM#7]
Dear Theo,

sorry for abusing the issue tracker for a stats question (if that's not OK, please close & delete!).

I have a study in 1D, where animals can move either upwards or downwards from a starting point.
The idea is to see at which distance they can spot some sweets and move directly upwards to the source.

I though to use moveHMM, but I can't get my head around how to model that.
Using a 3 state model I get the states that can be described as:
* Moving (either upwards or downwards)
* turning (change from upwards to downwards movement or vice versa)
* standing still (at the sweet source)

But this does not help me to answer my question:

I would like to have a model where I can model the movement downwards (something negative step-length?) and the movement upwards. 
With this I could use distance as covariate to get the distance where the animals spot the sweet and start moving upwards. So to incorporate the direction of the movement into the model?

Any ideas how I could model this?

**Comment by TheoMichelot** [comment]
Hi Eduard,

Thanks for your interest. If it's not related to a bug in moveHMM, I would prefer not to use the issue tracker. Would you mind getting in touch by email? (tmichelot1@sheffield.ac.uk)

Théo
